version: '3'
services:
  api:
    image: api:100
    restart: always
    ports:
      - "3000:3000"
    links: 
      - "mysql:db"
  mysql:
    image: "mysql:5.7"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: "!@#123"
    ports: 
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: